---
  header_logo_url: http://cockroach.speciesfile.org/HomePage/Cockroach/img_Logo/SiteLogo.jpg
  header_logo_text: Cockroach Species File
  header_links:
    - label: Home
      link: /

    - label: About
      link: /about
